name: Migration

on:
  push:
    paths:
    - DAL/Migrations/**

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    container:
      image: mysql:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run migrations
      run: mysql -h bef4oahbww6ootvomeaw-mysql.services.clever-cloud.com -u unq6tuny3kxylule -p RgUEHpzjVM8Q7OxXFsx1 bef4oahbww6ootvomeaw < DAL/Migrations/Script.sql  
